### ISSUE TITLE
failed to run on windows

### ISSUE THREAD

**Issue by xialang2012** [andre-schulz/mvs-texturing#1]
I built the windows version and run the run
`texrecon.exe nvmCams.nvm mesh.ply tex`, and it showed me

> C:\Users\xialang2012\Desktop\mvs-texturing\x64\Release>texrecon.exe nvmCams.nvm mesh.ply tex
> texrecon.exe (built on Jun 18 2016, 15:30:07)
> Load and prepare mesh:
> PLY Loader: comment PCL generated
> Reading PLY: 100002 verts... 199834 faces... done.
> Warning: Zero-length normals detected: 2 face normals, 0 vertex normals
> Generating texture views:
> 000000000000:
> 000000000000:
> NVM: Loading file...
> NVM: Number of views: 7
> NVM: Number of features: 0
> 
> ```
>     Loading 0%...
> ```

the data I used can be downloaded from the below link
`http://pan.baidu.com/s/1miiy04o`
Obviously, it blocked.
But when I tried on Linux, it works well. I think there must be some thing wrong about it.

**Comment by flanggut** [comment]
Hi there, Andre will be unavailable for the next ~8 weeks. We'll try to investigate this asap, but it can take a while.

**Comment by xialang2012** [comment]
Okay, thank you.

**Comment by xialang2012** [comment]
Besides, this command also failed on Windows

`texrecon bundle-res::undistorted odm_mesh.ply textured-odm`

when the out put as following:

> ```
>     Postprocessing face infos 100%... done. (Took 0.702s)
>     Maximum quality of a face within an image: 0
>     Clamping qualities to 0 within normalization.
>     Writing data cost file... done.
>     199834 faces have not been seen by a view.
>     Took: 30.352s
> ```
> 
> Generating texture patches:
>         Running... done. (Took 12.002s)
>         0 texture patches.
> Running global seam leveling:
>         Create matrices for optimization...  done.
>         Lhs dimensionality: 0 x 0
>         Calculating adjustments: 

It also showed a core dump messages when blending the results with a large input images number, great than 200.

**Comment by flanggut** [comment]
> `Maximum quality of a face within an image: 0`
> `199834 faces have not been seen by a view.`

This almost looks like the mesh doesn't project into the cameras of the scene? Adding @nmoehrle.

**Comment by xialang2012** [comment]
I have test it on Linux, and it works well.

**Comment by andre-schulz** [comment]
Hi @xialang2012,
do you still have this issue? If yes, can you please repost the dataset from your first post so I can try to reproduce the error?
Thanks in advance.

**Comment by xialang2012** [comment]
It works well now, thank you for your reply.

**Comment by hushanming** [comment]
Hi @xialang2012 ,
How do you solve this problem? I have encountered such a problem

**Comment by andre-schulz** [comment]
Hi @hushanming,
can you please describe in detail the problem you are encountering?

**Comment by hushanming** [comment]
I built the windows version and run the run
texrecon.exe bundle.nvm surface-clean.ply  tex, and it showed me

D:\data\der_hass-20140923>D:\vs2010\mvs-texturing\mvs-texturing-master\build_2013\apps\texrecon\Release\texrecon.exe bundle.nvm surface-clean.ply tex
D:\vs2010\mvs-texturing\mvs-texturing-master\build_2013\apps\texrecon\Release\texrecon.exe (built on Sep 16 2016, 09:43:19)

---

 Due to use of the -DRESEARCH=ON compile option, this program is licensed
 for research purposes only. Please pay special attention to the gco license.

---

Load and prepare mesh:
PLY Loader: comment Export generated by libmve
Reading PLY: 121043 verts... 238279 faces... done.
Generating texture views:
NVM: Loading file...
NVM: Number of views: 79
NVM: Number of features: 61172

and then it stop.
the data I used is [ Der Hass (79 images with bundle)](http://www.gris.tu-darmstadt.de/projects/mvs-texturing) on the official website

**Comment by debuleilei** [comment]
@xialang2012 I met a same problem like this:
Generating texture patches:
Running... done. (Took 12.002s)
0 texture patches.
Running global seam leveling:
Create matrices for optimization... done.
Lhs dimensionality: 0 x 0
Calculating adjustments: 
How do you solve this problem ?in windows，In linux the data works well!
