### ISSUE TITLE
How to create a debug version of this program

### ISSUE THREAD

**Issue by liaoksn** [andre-schulz/mvs-texturing#12]
Hi, andre
I have compiled a release version of this program, it works well with my input data . But when i use my data in debug version, it can't work , i.e some components of this program do not work. Do you have any suggestions on build a debug version of this program in visual studio ?

**Comment by andre-schulz** [comment]
Hi @zjulk,
I'm not 100% sure but after reading your issue in the main `mvs-texturing` repo (nmoehrle/mvs-texturing#189) I assume it might be because the debug build of `mvs-texturing` uses a release build of `libjpeg`. Can you try to compile/link a debug build of `mvs-texturing` against a debug build of `libjpeg`?

**Comment by liaoksn** [comment]
> Hi @zjulk, I'm not 100% sure but after reading your issue in the main `mvs-texturing` repo ([nmoehrle#189](https://github.com/nmoehrle/mvs-texturing/issues/189)) I assume it might be because the debug build of `mvs-texturing` uses a release build of `libjpeg`. Can you try to compile/link a debug build of `mvs-texturing` against a debug build of `libjpeg`?

I try to set CMAKE_CONFIGURATION_TYPES as _Debug;Release_ in the CmakeLists under 3rdparty, mve, recompiled it . Recompile mvs-texturing with this libs, then i can run a debug version of it successfully. Thanks for your reply.
